//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardPayment
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string CustomerName { get; set; }
        public string CVV { get; set; }
    }
}
