//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSpecialized
    {
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public int SpecializedId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
