//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenAppointmentSlot
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> From { get; set; }
        public Nullable<System.TimeSpan> To { get; set; }
        public Nullable<int> DoctorId { get; set; }
    }
}
